name: UltraBar
version: 2.4.0
main: com.ryandw11.ultrabar.UltraBar
author: Ryandw11
description: Send BossBars, Titles, and ActionBars to players.
softdepend: [WorldGuard, WorldEdit, PlaceholderAPI]
api-version: 1.13
commands:
    bar:
     description: Send boss bars to the entire server or specific players.
     aliases: [ubar, bossbar]
    utitle:
     description: Send titles to the entire server or specific players.
     aliases: [ut, ultratitle]
    actionbar:
     description: Send actionbars to the entire server or specific players.
     aliases: [ab, uactionbar, uab]
    UltraBar:
     description: The base command for UltraBar!
     aliases: [ub, ultrab]