############################################################
#                        UltraBar                          #
############################################################
#bstats is where data is sent. https://bstats.org/plugin/bukkit/UltraBar .
#Here is some more information on it like what it collects and how to disable it all togeather and not just for this plugin.
# https://bstats.org/getting-started
bstats: true
#If the plugin should check for updates. It will not if set to false. (Note: The plugin does not automaticly update.)
update_checker: true
#Note time is in seconds!
WorldGuardRegion:
    Enabled: true
    Message: '&6<< &b%region% &6>>'
    Message2: '&b%region% &3<<>> &6and &c%number%&6 more.'
############################################################
#                     Event Messages                       #
############################################################
OnJoin:
    BossBar:
        Enabled: true
        Message: '&6Welcome Back &5{player}&6!'
        Color: 'green'
        Time: 10
        Style: '6'
        Health: 1
    Title:
        Enabled: true
        Message: '&6Welcome Back &5{player}&6'
        SubTitle: '&bto the best server ever!'
        fadein: 5
        fadeout: 5
        time: 20
    ActionBar:
        Enabled: true
        Message: '&6Welcome Back &5{player}&6!'
        
OnDeath:
    BossBar:
        Enabled: true
        Message: '&6Welcome Back &5{player}&6!'
        Color: 'green'
        Time: 10
        Style: '6'
        Health: 1
    Title:
        Enabled: true
        Message: '&6Welcome Back &5{player}&6'
        SubTitle: '&bto the best server ever!'
        fadein: 5
        fadeout: 5
        time: 20
    ActionBar:
        Enabled: true
        Message: '&6Welcome Back &5{player}&6!'
        
OnCommand:
    list:
        - examplecmd
    examplecmd:
        BossBar:
            Message: '&6You ran a command!'
            Color: 'green'
            Time: 10
            Style: '6'
            Health: 1
        ActionBar:
            Message: '&6ActionBars can be used&6!'
        Title:
            Message: '&6Along with titles.&6'
            SubTitle: '&bThese support placeholderapi!'
            fadein: 5
            fadeout: 5
            time: 20
################################################################
#                        Anouncements                          #
################################################################
BossBarMessages:
    Enabled: true
    World_Whitelist_Enabled: false
    Random_Order: false
    World_Whitelist:
    - world
    Number_Of_Messages: 3
    1:
        Message: '&1BossBar #1'
        Color: 'green'
        Style: '6'
        Time: 10
    2:
        Message: '&2BossBar #2'
        Color: 'blue'
        Style: '6'
        Time: 10
    3:
        Message: '&3BossBar #3'
        Color: 'red'
        Style: '6'
        Time: 10
Title_Announcements:
    Enabled: false
    Random_Order: false
    Number_Of_Messages: 3
    Time: 20
    1:
        Message: '&6Message 1&6'
        SubTitle: '&bMeassage 1'
        fadein: 5
        fadeout: 5
        time: 20
    2:
        Message: '&6Message 2&6'
        SubTitle: '&bMessage 2'
        fadein: 5
        fadeout: 5
        time: 20
    3:
        Message: '&6Message 3&6'
        SubTitle: '&bMessage 3'
        fadein: 5
        fadeout: 5
        time: 20
Action_Announcements:
    Enabled: false
    Random_Order: false
    Number_Of_Messages: 3
    Time: 10
    1:
        Message: 'Message 1'
    2:
        Message: 'Message 2'
    3:
        Message: 'Message 3'